### ISSUE TITLE
Slice bounds out of range when running

### ISSUE THREAD

**Issue by DivineDominion** [rusq/osx-callhistory-decryptor#12]
👍  Opposed to the old Python script, this program does indeed run :)

I get an exception parsing the stuff, though: 

```
panic: runtime error: slice bounds out of range [:32] with capacity 24

goroutine 1 [running]:
github.com/rusq/osx-callhistory-decryptor/historydecryptor.Decipher({0x1400001e198?, 0x14?, 0x6?}, {0x1400001e120?, 0x126?, 0x0?})
	/Users/xxx/Downloads/osx-callhistory-decryptor/historydecryptor/historydecryptor.go:130 +0x210
github.com/rusq/osx-callhistory-decryptor/historydecryptor.DecipherHistory({0x14000018190, 0x46}, {0x1400001e120, 0x10, 0x12}, {0x10474f3f8?, 0x14000010018}, {0x14000127e90, 0x1, 0x1045743f4?})
	/Users/xxx/Downloads/osx-callhistory-decryptor/historydecryptor/historydecryptor.go:108 +0x5dc
main.run({0x140000180a0, 0x4a}, {0x0, 0x0}, {0x16b94b6c2, 0x18})
	/Users/xxx/Downloads/osx-callhistory-decryptor/main.go:106 +0x2cc
main.main()
	/Users/xxx/Downloads/osx-callhistory-decryptor/main.go:77 +0x138
exit status 2
```

Tried with interactive Keychain Access prompt, and using the `-k` parameter. Same error in both cases.

**Comment by rusq** [comment]
Hey @DivineDominion sorry meant to reply earlier, but completely forgot.  Thank you for the report.  I just tried this and can confirm.  Most likely they have changed how the cipher works on latest versions of OS since it was last attended to.
I will have a look, but can't promise it will work again any time soon.

**Comment by rusq** [comment]
Well, actually it looks like they have completely removed the encryption (even removed the key, see #13)

**Comment by rusq** [comment]
Please download the [new release](https://github.com/rusq/osx-callhistory-decryptor/releases/tag/v1.2.0), and run it with `-no-key` option.

It may require `sudo` as the CallHistory file is os protected.

**Comment by DivineDominion** [comment]
Thanks for looking into this! That makes sense; my call DB is not encrypted as well. (Other peoples' are still)
