### ISSUE TITLE
detailed explanation to run the project in windows

### ISSUE THREAD

**Issue by itsme-ach** [rusq/osx-callhistory-decryptor#18]
hi,

i am an absolutely new person to this world of coding, this is a project suggested to me by my friend.
i am tried and get how to run the project , so would you pls help me running this project from cloning to displaying the output of call history in windows . pls guide me through each and every step. hope you would solve me issues and guide me well.

thank you
itsme-ach

**Comment by rusq** [comment]
Hey, have you seen this section?

https://github.com/rusq/osx-callhistory-decryptor?tab=readme-ov-file#linux-windows-etc
