### ISSUE TITLE
Producing an empty CSV file

### ISSUE THREAD

**Issue by fi5u** [rusq/osx-callhistory-decryptor#8]
When I run:

`go run callhistory.go -o ~/Desktop/output-file.csv -f ../../../../data/calls/CallHistory.storedata`

The terminal prints the CSV and a CSV file is generated. However, the generated file is empty.

Using version 1.1.1

**Comment by rusq** [comment]
@fi5u could you please try the latest v1.1.2?

Note that command line invocation has changed (`-f` flag has been removed), in your case it would be:
```
go run . -o ~/Desktop/output-file.csv ../../../../data/calls/CallHistory.storedata
```

**Comment by fi5u** [comment]
@rusq Thanks for the quick fix, it works!
