### ISSUE TITLE
Key param not working

### ISSUE THREAD

**Issue by fi5u** [rusq/osx-callhistory-decryptor#9]
Hi, when I try to use the key param, I get the following error:

```
MacOS X Call History Decryptor v.0.0-development © 2018-2021 rusq
Based on Call History Decryptor © 2016 n0fate
2021/04/04 20:04:31 *** database filename: "/Users/tf/Library/Application Support/CallHistoryDB/CallHistory.storedata"
2021/04/04 20:04:31 *** temporary file (will be removed): "/var/folders/d5/7nrdxk_x3hsd1p4bk2bttf640000gn/T/callhistory351382213"
2021/04/04 20:04:31 illegal base64 data at input byte 8: make sure you have supplied the key via -k or KEY env variable
exit status 1
```

The call looks like this:

`go run . -k 2258D460-`

Any idea what might be causing this? There's only one key available from MacOS Keychain.

**Comment by rusq** [comment]
Hey @fi5u, thanks for reporting this.

The value you are passing to the `-k` parameter does not look like a valid key.

Valid key length should be 16 bytes (128 bits), i.e. (in this example I copied my base64-encoded key from the keychain to clipboard):
```
$ pbpaste | base64 -d | wc -c
      16
```

While the key you provided in the issue, is only 6 bytes:
```
$ echo '2258D460-' | base64 -d | wc -c
       6
```

My guess is that either the keychain value is corrupt or the wrong value is used.

Could you check if you're copying it from this location?  Here's the example from my computer:
<img width="890" alt="Screen Shot 2021-04-28 at 9 06 01 AM" src="https://user-images.githubusercontent.com/16064414/116312983-44584000-a801-11eb-9a66-bae21a90d63b.png">

**Comment by fi5u** [comment]
@rusq I'm sure that's where I checked for the keychain value previously. However, now when I checked it's in the correct format and it works. Many thanks for your help!
